fn main() {
    println!("cargo:rerun-if-changed=assets/app.rc");
    println!("cargo:rerun-if-changed=assets/app.ico");
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    // Generated by `cargo run --example make_icon`.
    if !std::path::Path::new("assets/app.ico").exists() {
        println!("cargo:warning=assets/app.ico missing, building without an app icon");
        return;
    }
    embed_resource::compile("assets/app.rc", embed_resource::NONE)
        .manifest_optional()
        .expect("embed app icon");
}
